import mods.jei.JEI;
import crafttweaker.item.IItemStack;


val itemToHide = [
	<thaumcraft:nugget>,
	<thaumcraft:nugget:1>,
	<thaumcraft:nugget:2>,
	<thaumcraft:nugget:3>,
	<thaumcraft:nugget:4>,

	<mod_lavacow:mossy_stick>,

	<itemfilters:filter>,


] as IItemStack[];


for item in itemToHide {
	JEI.removeAndHide(item);
}

val itemsToRemove = [
	<embers:geo_separator>,
	<embers:seed_gold>,
	<embers:ingot_tin>,
	<embers:plate_tin>,
	<embers:nugget_tin>,
	<embers:ore_tin>,
	<embers:seed_tin>,
	<embers:block_tin>,

	<embers:pickaxe_copper:*>,
	<embers:axe_copper:*>,
	<embers:shovel_copper:*>,
	<embers:hoe_copper:*>,
	<embers:sword_copper:*>,
	<embers:pickaxe_silver:*>,
	<embers:axe_silver:*>,
	<embers:shovel_silver:*>,
	<embers:hoe_silver:*>,
	<embers:sword_silver:*>,
	<embers:pickaxe_lead:*>,
	<embers:axe_lead:*>,
	<embers:shovel_lead:*>,
	<embers:hoe_lead:*>,
	<embers:sword_lead:*>,
	<embers:pickaxe_dawnstone:*>,
	<embers:axe_dawnstone:*>,
	<embers:shovel_dawnstone:*>,
	<embers:hoe_dawnstone:*>,
	<embers:sword_dawnstone:*>,
	<embers:pickaxe_aluminum:*>,
	<embers:axe_aluminum:*>,
	<embers:shovel_aluminum:*>,
	<embers:sword_aluminum:*>,
	<embers:hoe_aluminum:*>,
	<embers:pickaxe_bronze:*>,
	<embers:axe_bronze:*>,
	<embers:shovel_bronze:*>,
	<embers:sword_bronze:*>,
	<embers:hoe_bronze:*>,
	<embers:pickaxe_electrum:*>,
	<embers:axe_electrum:*>,
	<embers:shovel_electrum:*>,
	<embers:sword_electrum:*>,
	<embers:hoe_electrum:*>,
	<embers:pickaxe_nickel:*>,
	<embers:axe_nickel:*>,
	<embers:shovel_nickel:*>,
	<embers:sword_nickel:*>,
	<embers:hoe_nickel:*>,
	<embers:pickaxe_tin:*>,
	<embers:axe_tin:*>,
	<embers:shovel_tin:*>,
	<embers:sword_tin:*>,
	<embers:hoe_tin:*>,
	<embers:isolated_materia>,

	<jaopca:item_platedensealuminium>,
	<jaopca:item_platedensecopper>,
	<jaopca:item_platedensegold>,
	<jaopca:item_platedenseiron>,
	<jaopca:item_platedenselead>,
	<jaopca:item_platedensenickel>,
	<jaopca:item_platedenseoctine>,
	<jaopca:item_platedensesilver>,
	<jaopca:item_platedensesyrmorite>,
	<jaopca:item_platedensetin>,
	<jaopca:item_platedensebrass>,
	<jaopca:item_platedensebronze>,
	<jaopca:item_platedensedawnstone>,
	<jaopca:item_platedenseelectrum>,
	<jaopca:item_platedensethaumium>,
	<jaopca:item_platedensevoid>,

	<quark:color_slime:1>,
	<quark:color_slime:2>,
	<quark:color_slime:3>,
	<quark:color_slime:4>,
	<quark:glass_item_frame>,
	<quark:spruce_trapdoor>,
	<quark:birch_trapdoor>,
	<quark:jungle_trapdoor>,
	<quark:acacia_trapdoor>,
	<quark:dark_oak_trapdoor>,
	<quark:color_slime>,
	<quark:lit_lamp>,
	<quark:backpack>,
	<quark:hardened_clay_tiles:*>,
	<quark:hardened_clay_tiles_stairs>,
	<quark:hardened_clay_tiles_slab>,
	<quark:stained_clay_tiles:*>,
	<quark:stained_clay_tiles_white_stairs>,
	<quark:stained_clay_tiles_orange_stairs>,
	<quark:stained_clay_tiles_magenta_stairs>,
	<quark:stained_clay_tiles_light_blue_stairs>,
	<quark:stained_clay_tiles_yellow_stairs>,
	<quark:stained_clay_tiles_lime_stairs>,
	<quark:stained_clay_tiles_pink_stairs>,
	<quark:stained_clay_tiles_gray_stairs>,
	<quark:stained_clay_tiles_silver_stairs>,
	<quark:stained_clay_tiles_cyan_stairs>,
	<quark:stained_clay_tiles_purple_stairs>,
	<quark:stained_clay_tiles_blue_stairs>,
	<quark:stained_clay_tiles_brown_stairs>,
	<quark:stained_clay_tiles_green_stairs>,
	<quark:stained_clay_tiles_red_stairs>,
	<quark:stained_clay_tiles_black_stairs>,
	<quark:stained_clay_tiles_white_slab>,
	<quark:stained_clay_tiles_orange_slab>,
	<quark:stained_clay_tiles_magenta_slab>,
	<quark:stained_clay_tiles_light_blue_slab>,
	<quark:stained_clay_tiles_yellow_slab>,
	<quark:stained_clay_tiles_lime_slab>,
	<quark:stained_clay_tiles_pink_slab>,
	<quark:stained_clay_tiles_gray_slab>,
	<quark:stained_clay_tiles_silver_slab>,
	<quark:stained_clay_tiles_cyan_slab>,
	<quark:stained_clay_tiles_purple_slab>,
	<quark:stained_clay_tiles_blue_slab>,
	<quark:stained_clay_tiles_brown_slab>,
	<quark:stained_clay_tiles_green_slab>,
	<quark:stained_clay_tiles_red_slab>,
	<quark:stained_clay_tiles_black_slab>,
	<quark:stone_stairs>,
	<quark:stone_granite_stairs>,
	<quark:stone_granite_slab>,
	<quark:stone_diorite_stairs>,
	<quark:stone_diorite_slab>,
	<quark:stone_andesite_stairs>,
	<quark:stone_andesite_slab>,
	<quark:end_bricks_stairs>,
	<quark:end_bricks_slab>,
	<quark:prismarine_stairs>,
	<quark:prismarine_slab>,
	<quark:prismarine_bricks_stairs>,
	<quark:prismarine_bricks_slab>,
	<quark:prismarine_dark_stairs>,
	<quark:prismarine_dark_slab>,
	<quark:red_nether_brick_stairs>,
	<quark:red_nether_brick_slab>,
	<quark:cobblestone_mossy_stairs>,
	<quark:cobblestone_mossy_slab>,
	<quark:stonebrick_mossy_stairs>,
	<quark:stonebrick_mossy_slab>,
	<quark:thatch>,
	<quark:thatch_stairs>,
	<quark:thatch_slab>,
	<quark:world_stone_bricks>,
	<quark:world_stone_bricks:1>,
	<quark:world_stone_bricks:2>,
	<quark:world_stone_carved>,
	<quark:world_stone_carved:1>,
	<quark:world_stone_carved:2>,
	<quark:stone_granite_bricks_stairs>,
	<quark:stone_granite_bricks_slab>,
	<quark:stone_diorite_bricks_stairs>,
	<quark:stone_diorite_bricks_slab>,
	<quark:stone_andesite_bricks_stairs>,
	<quark:stone_andesite_bricks_slab>,
	<quark:midori_block>,
	<quark:midori_pillar>,
	<quark:midori_block_stairs>,
	<quark:midori_block_slab>,
	<quark:world_stone_pavement>,
	<quark:world_stone_pavement:1>,
	<quark:world_stone_pavement:2>,
	<quark:reed_block>,
	<quark:reed_block_stairs>,
	<quark:reed_block_slab>,
	<quark:turf>,
	<quark:turf_stairs>,
	<quark:turf_slab>,
	<quark:blaze_lantern>,
	<quark:stone_granite_bricks_wall>,
	<quark:stone_diorite_bricks_wall>,
	<quark:stone_andesite_bricks_wall>,
	<quark:midori_block_wall>,
	<quark:reed_block_wall>,
	<quark:paper_wall>,
	<quark:paper_wall_big>,
	<quark:paper_wall_sakura>,
	<quark:leaf_carpet:5>,
	<quark:leaf_carpet>,
	<quark:leaf_carpet:1>,
	<quark:leaf_carpet:2>,
	<quark:leaf_carpet:3>,
	<quark:leaf_carpet:4>,
	<quark:rope>,
	<quark:colored_flowerpot_white>,
	<quark:colored_flowerpot_orange>,
	<quark:colored_flowerpot_magenta>,
	<quark:colored_flowerpot_light_blue>,
	<quark:colored_flowerpot_yellow>,
	<quark:colored_flowerpot_lime>,
	<quark:colored_flowerpot_pink>,
	<quark:colored_flowerpot_gray>,
	<quark:colored_flowerpot_silver>,
	<quark:colored_flowerpot_cyan>,
	<quark:colored_flowerpot_purple>,
	<quark:colored_flowerpot_blue>,
	<quark:colored_flowerpot_brown>,
	<quark:colored_flowerpot_green>,
	<quark:colored_flowerpot_red>,
	<quark:colored_flowerpot_black>,

	<ftbquests:screen>,
	<ftbquests:progress_detector>,
	<ftbquests:detector>,
	<ftbquests:detector:1>,
	<ftbquests:progress_screen>,
	<ftbquests:chest>,
	<ftbquests:loot_crate_storage>,
	<ftbquests:loot_crate_opener>,
	<ftbquests:barrier>,
	<ftbquests:reward_collector>,

	//<mystgears:gear_copper>,
] as IItemStack[];


for item in itemsToRemove {
	JEI.removeAndHide(item);
	item.removeAspects(allAspects);
}



