#priority 400
import thaumcraft.aspect.CTAspectStack;

<thebetweenlands:betweenstone>.setAspects(<aspect:perditio> * 1, <aspect:terra> * 5);
<thebetweenlands:mud>.setAspects(<aspect:aqua> * 5, <aspect:terra> * 5);
<thebetweenlands:peat>.setAspects(<aspect:ignis> * 5, <aspect:terra> * 5);
<thebetweenlands:sludgy_dirt>.setAspects(<aspect:terra> * 5, <aspect:vinculum> * 2);
<thebetweenlands:cragrock>.setAspects(<aspect:perditio> * 1, <aspect:terra> * 5);
<thebetweenlands:cragrock:1>.setAspects(<aspect:perditio> * 1, <aspect:terra> * 3, <aspect:herba> * 5);
<thebetweenlands:cragrock:2>.setAspects(<aspect:perditio> * 1, <aspect:terra> * 5, <aspect:herba> * 3);
<thebetweenlands:pitstone>.setAspects(<aspect:perditio> * 1, <aspect:terra> * 5);
<thebetweenlands:limestone>.setAspects(<aspect:perditio> * 1, <aspect:terra> * 5);
<thebetweenlands:coarse_swamp_dirt>.setAspects(<aspect:terra> * 3);
<thebetweenlands:wisp>.setAspects(<aspect:ignis> * 3, <aspect:lux> * 10, <aspect:potentia> * 2, <aspect:sensus> * 5);
<thebetweenlands:octine_ore>.setAspects(<aspect:ignis> * 15, <aspect:terra> * 5, <aspect:metallum> * 10);
<thebetweenlands:valonite_ore>.setAspects(<aspect:terra> * 5, <aspect:vitreus> * 15, <aspect:desiderium> * 15);
<thebetweenlands:sulfur_ore>.setAspects(<aspect:ignis> * 15, <aspect:terra> * 5, <aspect:potentia> * 15);
<thebetweenlands:slimy_bone_ore>.setAspects(<aspect:terra> * 5, <aspect:mortuus> * 5, <aspect:victus> * 5);
<thebetweenlands:scabyst_ore>.setAspects(<aspect:ordo> * 15, <aspect:terra> * 5);
<thebetweenlands:syrmorite_ore>.setAspects(<aspect:terra> * 5, <aspect:metallum> * 15);
<thebetweenlands:aqua_middle_gem_ore>.setAspects(<aspect:aqua> * 10, <aspect:terra> * 10, <aspect:vitreus> * 5);
<thebetweenlands:crimson_middle_gem_ore>.setAspects(<aspect:aqua> * 10, <aspect:terra> * 10, <aspect:vitreus> * 5);
<thebetweenlands:green_middle_gem_ore>.setAspects(<aspect:aqua> * 10, <aspect:terra> * 10, <aspect:vitreus> * 5);
<thebetweenlands:dead_grass>.setAspects(<aspect:terra> * 3, <aspect:herba> * 1);
<thebetweenlands:tar_solid>.setAspects(<aspect:terra> * 5, <aspect:tenebrae> * 5);
<thebetweenlands:log_rotten_bark>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rubber>.setAspects(<aspect:herba> * 10, <aspect:vinculum> * 5);
<thebetweenlands:log_hearthgrove:1>.setAspects(<aspect:ignis> * 2, <aspect:herba> * 20);
<thebetweenlands:log_hearthgrove:2>.setAspects(<aspect:ignis> * 2, <aspect:herba> * 20);
<thebetweenlands:log_hearthgrove:5>.setAspects(<aspect:ignis> * 2, <aspect:herba> * 18, <aspect:tenebrae> * 2);
<thebetweenlands:log_hearthgrove:7>.setAspects(<aspect:ignis> * 2, <aspect:herba> * 18, <aspect:tenebrae> * 2);
<thebetweenlands:log_nibbletwig>.setAspects(<aspect:herba> * 10, <aspect:cognitio> * 5);
<thebetweenlands:log_spirit_tree>.setAspects(<aspect:victus> * 5, <aspect:herba> * 10, <aspect:spiritus> * 5);
<thebetweenlands:log_sap>.setAspects(<aspect:aqua> * 2, <aspect:victus> * 3, <aspect:herba> * 10);
<thebetweenlands:sapling_spirit_tree>.setAspects(<aspect:victus> * 5, <aspect:herba> * 15, <aspect:spiritus> * 5, <aspect:auram> * 5, <aspect:sensus> * 5);
<thebetweenlands:root_pod>.setAspects(<aspect:victus> * 5, <aspect:herba> * 15);
<thebetweenlands:betweenstone_tiles>.setAspects(<aspect:ordo> * 1, <aspect:terra> * 3);
<thebetweenlands:betweenstone_chiseled>.setAspects(<aspect:ordo> * 1, <aspect:terra> * 1);
<thebetweenlands:cragrock_chiseled>.setAspects(<aspect:ordo> * 1, <aspect:terra> * 1);
<thebetweenlands:limestone_chiseled>.setAspects(<aspect:ordo> * 1, <aspect:terra> * 1);
<thebetweenlands:pitstone_chiseled>.setAspects(<aspect:ordo> * 1, <aspect:terra> * 1);
<thebetweenlands:scabyst_chiseled_1>.setAspects(<aspect:ordo> * 1);
<thebetweenlands:scabyst_chiseled_2>.setAspects(<aspect:ordo> * 1);
<thebetweenlands:scabyst_chiseled_3>.setAspects(<aspect:ordo> * 1);
<thebetweenlands:cracked_betweenstone_bricks>.setAspects(<aspect:ordo> * 1, <aspect:terra> * 3);
<thebetweenlands:cracked_betweenstone_tiles>.setAspects(<aspect:ordo> * 1, <aspect:terra> * 3);
<thebetweenlands:cracked_limestone_bricks>.setAspects(<aspect:ordo> * 1, <aspect:terra> * 3);
<thebetweenlands:glowing_betweenstone_tile>.setAspects(<aspect:ordo> * 1, <aspect:terra> * 3, <aspect:lux> * 15);
<thebetweenlands:glowing_smooth_cragrock>.setAspects(<aspect:terra> * 5, <aspect:lux> * 15);
<thebetweenlands:polished_limestone>.setAspects(<aspect:terra> * 5);
<thebetweenlands:smooth_betweenstone>.setAspects(<aspect:terra> * 5);
<thebetweenlands:smooth_cragrock>.setAspects(<aspect:terra> * 5);
<thebetweenlands:octine_block>.setAspects(<aspect:ignis> * 101, <aspect:metallum> * 67);
<thebetweenlands:syrmorite_block>.setAspects(<aspect:metallum> * 101);
<thebetweenlands:valonite_block>.setAspects(<aspect:vitreus> * 101, <aspect:desiderium> * 101);
<thebetweenlands:smooth_pitstone>.setAspects(<aspect:terra> * 5);
<thebetweenlands:polished_dentrothyst:0>.setAspects(<aspect:ordo> * 5, <aspect:vitreus> * 15, <aspect:praecantatio> * 5);
<thebetweenlands:polished_dentrothyst:1>.setAspects(<aspect:ordo> * 5, <aspect:vitreus> * 15, <aspect:praecantatio> * 10);
<thebetweenlands:amate_paper_pane_1>.setAspects(<aspect:herba> * 5);
<thebetweenlands:amate_paper_pane_2>.setAspects(<aspect:herba> * 5);
<thebetweenlands:amate_paper_pane_3>.setAspects(<aspect:herba> * 5);
<thebetweenlands:mud_bricks_carved:5>.setAspects(<aspect:ignis> * 3, <aspect:ordo> * 3, <aspect:terra> * 19);
<thebetweenlands:mud_bricks_carved:6>.setAspects(<aspect:aqua> * 3, <aspect:ignis> * 2, <aspect:ordo> * 2, <aspect:terra> * 15, <aspect:victus> * 3);
<thebetweenlands:mud_bricks_carved:7>.setAspects(<aspect:aqua> * 6, <aspect:ignis> * 1, <aspect:ordo> * 1, <aspect:terra> * 11, <aspect:victus> * 9);
<thebetweenlands:mud_bricks_carved:8>.setAspects(<aspect:aqua> * 9, <aspect:terra> * 9, <aspect:victus> * 9);
<thebetweenlands:mud_bricks_carved:9>.setAspects(<aspect:aqua> * 10, <aspect:terra> * 7, <aspect:victus> * 10);
<thebetweenlands:edge_shroom>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 5, <aspect:tenebrae> * 2);
<thebetweenlands:edge_moss>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 7);
<thebetweenlands:edge_leaf>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:mud_bricks_climbable>.setAspects(<aspect:ignis> * 3, <aspect:ordo> * 3, <aspect:terra> * 15);
<thebetweenlands:dungeon_wall_candle>.setAspects(<aspect:ordo> * 2, <aspect:terra> * 11, <aspect:lux> * 5);
<thebetweenlands:wooden_support_beam_rotten_1>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 5, <aspect:fabrico> * 5);
<thebetweenlands:wooden_support_beam_rotten_2>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 5, <aspect:fabrico> * 5);
<thebetweenlands:wooden_support_beam_rotten_3>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 5, <aspect:fabrico> * 5);
<thebetweenlands:log_rotten_bark_carved_1>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_2>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_3>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_4>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_5>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_6>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_7>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_8>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_9>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_10>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_11>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_12>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_13>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_14>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_15>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:log_rotten_bark_carved_16>.setAspects(<aspect:ordo> * 2, <aspect:mortuus> * 2, <aspect:herba> * 10);
<thebetweenlands:mud_tower_brazier>.setAspects(<aspect:ignis> * 20, <aspect:lux> * 30, <aspect:herba> * 10);
<thebetweenlands:pitcher_plant>.setAspects(<aspect:aqua> * 3, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:weeping_blue>.setAspects(<aspect:ordo> * 3, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:sundew>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:black_hat_mushroom>.setAspects(<aspect:herba> * 5, <aspect:tenebrae> * 2);
<thebetweenlands:bulb_capped_mushroom>.setAspects(<aspect:lux> * 2, <aspect:herba> * 5);
<thebetweenlands:flat_head_mushroom>.setAspects(<aspect:ordo> * 2, <aspect:herba> * 5);
<thebetweenlands:venus_fly_trap>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:vinculum> * 3, <aspect:sensus> * 5);
<thebetweenlands:volarpad>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:volatus> * 3, <aspect:sensus> * 5);
<thebetweenlands:swamp_plant>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:swamp_kelp>.setAspects(<aspect:aqua> * 1, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:mire_coral>.setAspects(<aspect:aqua> * 3, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:deep_water_coral>.setAspects(<aspect:aqua> * 3, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:water_weeds>.setAspects(<aspect:aqua> * 1, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:shelf_fungus>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:algae>.setAspects(<aspect:aqua> * 2, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:poison_ivy>.setAspects(<aspect:mortuus> * 2, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:arrow_arum>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:blue_eyed_grass>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:blue_iris>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:boneset>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:bottle_brush_grass>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:broomsedge>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:button_bush>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:cardinal_flower>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:cattail>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:cave_grass>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:copper_iris>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:marsh_hibiscus>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:marsh_mallow>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:bladderwort_flower>.setAspects(<aspect:aqua> * 2, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:bladderwort_stalk>.setAspects(<aspect:aqua> * 1, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:bog_bean_flower>.setAspects(<aspect:aqua> * 2, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:bog_bean_stalk>.setAspects(<aspect:aqua> * 1, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:golden_club_flower>.setAspects(<aspect:aqua> * 2, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:golden_club_stalk>.setAspects(<aspect:aqua> * 1, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:marsh_marigold_flower>.setAspects(<aspect:aqua> * 2, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:marsh_marigold_stalk>.setAspects(<aspect:aqua> * 1, <aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:swamp_double_tallgrass>.setAspects(<aspect:aer> * 1, <aspect:herba> * 5);
<thebetweenlands:milkweed>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:nettle>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:aversio> * 1, <aspect:sensus> * 5);
<thebetweenlands:nettle_flowered>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:aversio> * 1, <aspect:sensus> * 5);
<thebetweenlands:pickerel_weed>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:phragmites>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:shoots>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:sludgecreep>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:tall_sludgecreep>.setAspects(<aspect:mortuus> * 3, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:soft_rush>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:thorns>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:aversio> * 1, <aspect:sensus> * 5);
<thebetweenlands:tall_cattail>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:swamp_tallgrass>.setAspects(<aspect:aer> * 1, <aspect:herba> * 5);
<thebetweenlands:dead_weedwood_bush>.setAspects(<aspect:mortuus> * 1, <aspect:herba> * 5);
<thebetweenlands:weedwood_bush>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:cave_moss>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5);
<thebetweenlands:cryptweed>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:string_roots>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:pale_grass>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:rotbulb>.setAspects(<aspect:mortuus> * 2, <aspect:herba> * 5, <aspect:sensus> * 5);
<thebetweenlands:moss>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5);
<thebetweenlands:dead_moss>.setAspects(<aspect:herba> * 5);
<thebetweenlands:lichen>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5);
<thebetweenlands:dead_lichen>.setAspects(<aspect:herba> * 5);
<thebetweenlands:hanger>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5);
<thebetweenlands:middle_fruit_bush>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5);
<thebetweenlands:purified_swamp_dirt>.setAspects(<aspect:ordo> * 3, <aspect:terra> * 5);
<thebetweenlands:black_ice>.setAspects(<aspect:gelum> * 20);
<thebetweenlands:snow>.setAspects(<aspect:gelum> * 1);
<thebetweenlands:weedwood_workbench>.setAspects(<aspect:herba> * 9, <aspect:fabrico> * 20);
<thebetweenlands:sulfur_furnace>.setAspects(<aspect:ignis> * 10, <aspect:perditio> * 6, <aspect:terra> * 30);
<thebetweenlands:sulfur_furnace_active>.setAspects(<aspect:ignis> * 10, <aspect:perditio> * 6, <aspect:terra> * 30);
<thebetweenlands:weedwood_jukebox>.setAspects(<aspect:aer> * 15, <aspect:vitreus> * 11, <aspect:herba> * 18, <aspect:desiderium> * 11, <aspect:machina> * 10, <aspect:sensus> * 20);
<thebetweenlands:fallen_leaves>.setAspects(<aspect:herba> * 3);
<thebetweenlands:weedwood_door>.setAspects(<aspect:herba> * 4, <aspect:vinculum> * 5, <aspect:machina> * 5);
<thebetweenlands:rubber_tree_plank_door>.setAspects(<aspect:herba> * 1, <aspect:vinculum> * 6, <aspect:machina> * 5);
<thebetweenlands:giant_root_plank_door>.setAspects(<aspect:herba> * 4, <aspect:vinculum> * 5, <aspect:machina> * 5);
<thebetweenlands:hearthgrove_plank_door>.setAspects(<aspect:herba> * 4, <aspect:vinculum> * 5, <aspect:machina> * 5);
<thebetweenlands:nibbletwig_plank_door>.setAspects(<aspect:herba> * 1, <aspect:vinculum> * 5, <aspect:cognitio> * 1, <aspect:machina> * 5);
<thebetweenlands:syrmorite_door>.setAspects(<aspect:herba> * 22, <aspect:vinculum> * 5, <aspect:machina> * 5);
<thebetweenlands:scabyst_door>.setAspects(<aspect:ordo> * 7, <aspect:vitreus> * 4, <aspect:vinculum> * 5, <aspect:machina> * 5);
<thebetweenlands:sulfur_torch_extinguished>.setAspects(<aspect:tenebrae> * 2);
<thebetweenlands:sulfur_torch>.setAspects(<aspect:ignis> * 1, <aspect:lux> * 5, <aspect:potentia> * 1);
<thebetweenlands:weedwood_trapdoor>.setAspects(<aspect:motus> * 5, <aspect:herba> * 6);
<thebetweenlands:rubber_tree_plank_trapdoor>.setAspects(<aspect:motus> * 5, <aspect:herba> * 2, <aspect:vinculum> * 2);
<thebetweenlands:syrmorite_trapdoor>.setAspects(<aspect:metallum> * 45, <aspect:motus> * 5);
<thebetweenlands:giant_root_plank_trapdoor>.setAspects(<aspect:motus> * 5, <aspect:herba> * 6);
<thebetweenlands:hearthgrove_plank_trapdoor>.setAspects(<aspect:motus> * 5, <aspect:herba> * 6);
<thebetweenlands:nibbletwig_plank_trapdoor>.setAspects(<aspect:motus> * 5, <aspect:herba> * 2, <aspect:cognitio> * 2);
<thebetweenlands:scabyst_trapdoor>.setAspects(<aspect:ordo> * 11, <aspect:motus> * 5, <aspect:vitreus> * 6);
<thebetweenlands:wood_chip_path>.setAspects(<aspect:herba> * 2);
<thebetweenlands:simulacrum_deepman>.setAspects(<aspect:terra> * 30, <aspect:auram> * 5, <aspect:sensus> * 20);
<thebetweenlands:simulacrum_lake_cavern>.setAspects(<aspect:aqua> * 30, <aspect:auram> * 5, <aspect:sensus> * 20);
<thebetweenlands:simulacrum_rootman>.setAspects(<aspect:herba> * 30, <aspect:auram> * 5, <aspect:sensus> * 20);
<thebetweenlands:offering_table>.setAspects(<aspect:ordo> * 10, <aspect:terra> * 20, <aspect:praecantatio> * 10);
<thebetweenlands:lantern_paper_1>.setAspects(<aspect:lux> * 10, <aspect:herba> * 15, <aspect:fabrico> * 3);
<thebetweenlands:lantern_paper_2>.setAspects(<aspect:lux> * 10, <aspect:herba> * 15, <aspect:fabrico> * 3);
<thebetweenlands:lantern_paper_3>.setAspects(<aspect:lux> * 10, <aspect:herba> * 15, <aspect:fabrico> * 3);
<thebetweenlands:items_crushed:*>.setAspects(<aspect:herba> * 5, <aspect:alkimia> * 2);
<thebetweenlands:items_crushed:28>.setAspects(<aspect:vitreus> * 5, <aspect:alkimia> * 2);
<thebetweenlands:items_crushed:32>.setAspects(<aspect:vitreus> * 5, <aspect:alkimia> * 2);
<thebetweenlands:items_crushed:45>.setAspects(<aspect:vitreus> * 5, <aspect:alkimia> * 2);
<thebetweenlands:items_plant_drop:*>.setAspects(<aspect:victus> * 1, <aspect:herba> * 5);
<thebetweenlands:dentrothyst_shard_orange>.setAspects(<aspect:vitreus> * 5, <aspect:praecantatio> * 5);
<thebetweenlands:dentrothyst_shard_green>.setAspects(<aspect:vitreus> * 5, <aspect:praecantatio> * 3);
<thebetweenlands:sap_ball>.setAspects(<aspect:aqua> * 5, <aspect:victus> * 5);
<thebetweenlands:wight_heart>.setAspects(<aspect:exanimis> * 5, <aspect:spiritus> * 10, <aspect:alienis> * 10);
<thebetweenlands:crimson_middle_gem>.setAspects(<aspect:vitreus> * 5, <aspect:praecantatio> * 5);
<thebetweenlands:aqua_middle_gem>.setAspects(<aspect:vitreus> * 5, <aspect:praecantatio> * 5);
<thebetweenlands:green_middle_gem>.setAspects(<aspect:vitreus> * 5, <aspect:praecantatio> * 5);
<thebetweenlands:life_crystal>.setAspects(<aspect:victus> * 20, <aspect:vitreus> * 5, <aspect:praecantatio> * 20, <aspect:spiritus> * 10);
<thebetweenlands:pyrad_flame>.setAspects(<aspect:victus> * 15, <aspect:vitreus> * 3, <aspect:praecantatio> * 15, <aspect:spiritus> * 7);
<thebetweenlands:pyrad_flame>.setAspects(<aspect:ignis> * 10, <aspect:spiritus> * 5);
<thebetweenlands:critter>.setAspects(<aspect:bestia> * 5, <aspect:cognitio> * 5, <aspect:sensus> * 5);
<thebetweenlands:octine_ingot>.setAspects(<aspect:ignis> * 15, <aspect:metallum> * 10);
<thebetweenlands:items_misc:0>.setAspects(<aspect:aqua> * 5, <aspect:vinculum> * 2, <aspect:praemunio> * 5);
<thebetweenlands:items_misc:1>.setAspects(<aspect:aqua> * 5, <aspect:vinculum> * 2, <aspect:praemunio> * 5);
<thebetweenlands:items_misc:2>.setAspects(<aspect:victus> * 2, <aspect:herba> * 1);
<thebetweenlands:items_misc:3>.setAspects(<aspect:aer> * 5, <aspect:volatus> * 5);
<thebetweenlands:items_misc:4>.setAspects(<aspect:bestia> * 5, <aspect:praemunio> * 5);
<thebetweenlands:items_misc:6>.setAspects(<aspect:aer> * 2, <aspect:herba> * 5);
<thebetweenlands:items_misc:10>.setAspects(<aspect:ignis> * 1, <aspect:ordo> * 1, <aspect:terra> * 5);
<thebetweenlands:items_misc:11>.setAspects(<aspect:metallum> * 15);
<thebetweenlands:items_misc:13>.setAspects(<aspect:herba> * 10);
<thebetweenlands:items_misc:14>.setAspects(<aspect:mortuus> * 5, <aspect:victus> * 5);
<thebetweenlands:items_misc:17>.setAspects(<aspect:mortuus> * 5, <aspect:bestia> * 5, <aspect:sensus> * 5);
<thebetweenlands:items_misc:18>.setAspects(<aspect:ignis> * 10, <aspect:potentia> * 10);
<thebetweenlands:items_misc:19>.setAspects(<aspect:vitreus> * 15, <aspect:desiderium> * 15);
<thebetweenlands:items_misc:21>.setAspects(<aspect:bestia> * 5, <aspect:aversio> * 2);
<thebetweenlands:items_misc:23>.setAspects(<aspect:herba> * 2, <aspect:vinculum> * 2);
<thebetweenlands:items_misc:25>.setAspects(<aspect:aqua> * 12, <aspect:victus> * 3, <aspect:spiritus> * 7, <aspect:tenebrae> * 30, <aspect:vinculum> * 30, <aspect:alienis> * 7);
<thebetweenlands:items_misc:26>.setAspects(<aspect:aqua> * 2, <aspect:tenebrae> * 5, <aspect:vinculum> * 5);
<thebetweenlands:items_misc:27>.setAspects(<aspect:terra> * 1);
<thebetweenlands:items_misc:30>.setAspects(<aspect:mortuus> * 3, <aspect:bestia> * 5);
<thebetweenlands:items_misc:32>.setAspects(<aspect:herba> * 3, <aspect:cognitio> * 2);
<thebetweenlands:items_misc:38>.setAspects(<aspect:praecantatio> * 3, <aspect:fabrico> * 5);
<thebetweenlands:items_misc:39>.setAspects(<aspect:ordo> * 5, <aspect:vitreus> * 3);
<thebetweenlands:items_misc:41>.setAspects(<aspect:metallum> * 1);
<thebetweenlands:items_misc:42>.setAspects(<aspect:ignis> * 1);
<thebetweenlands:items_misc:43>.setAspects(<aspect:vitreus> * 1, <aspect:desiderium> * 1);
<thebetweenlands:items_misc:44>.setAspects(<aspect:exanimis> * 10, <aspect:spiritus> * 10);
<thebetweenlands:items_misc:45>.setAspects(<aspect:ignis> * 10, <aspect:vitreus> * 3);
<thebetweenlands:items_misc:47>.setAspects(<aspect:vitreus> * 5, <aspect:alienis> * 5);





<minecraft:dye:0>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:1>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:2>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:3>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:4>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:5>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:6>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:7>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:8>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:9>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:10>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:11>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:12>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:13>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:14>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);
<minecraft:dye:15>.setAspects(<aspect:sensus> * 5, <aspect:perditio> * 2);


for item in <ore:allFlowers>.items {
	item.setAspects(<aspect:herba> * 5, <aspect:sensus> * 5, <aspect:victus> * 5);
}
